### ISSUE TITLE
Remove unused code 

### ISSUE THREAD

**Issue by keikeka** [cornensue/The-Excuse-Generator#1]
Cornelio, 
The project is approved but remember not to repeat code. 
You can delete from line 21 to 23 since you are not using this code, but inside the function. 

https://github.com/cornensue/The-Excuse-Generator/blob/b196ddd24c762dfd7a66656e4ea7195d1b3b9917/src/app.js#L21

**Comment by cornensue** [comment]
Hello, 

Keili, thanks. Ok I will remove them.

**Comment by keikeka** [comment]
Perfect! 
I will close issue.
